import type { ConfigObject, ConfigOptions } from "../types";
import { interopDefault, isEnabled, mapRules } from "../utils";

/**
@see https://github.com/sindresorhus/eslint-plugin-unicorn#rules
*/
export async function unicorn(options: ConfigOptions): Promise<Partial<ConfigObject>> {
  if (!isEnabled(options.features, "unicorn")) return {};

  const plugin = await interopDefault(import("eslint-plugin-unicorn"));

  const overrides = mapRules(options.overrides?.unicorn ?? {}, (rule, value) => {
    if (rule.startsWith("unicorn/")) {
      return [rule, value];
    }
    else {
      return [`unicorn/${rule}`, value];
    }
  });

  return {
    plugins: { unicorn: plugin },
    rules: {
      "unicorn/better-dom-traversing": "error",
      "unicorn/catch-error-name": ["error", { name: "err" }],
      "unicorn/consistent-conditional-object-spread": ["error", "logical"],
      "unicorn/consistent-date-clone": "error",
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/consistent-existence-index-check": "error",
      "unicorn/consistent-function-scoping": ["error", { checkArrowFunctions: false }],
      "unicorn/consistent-tuple-labels": "error",
      "unicorn/custom-error-definition": "error",
      "unicorn/dom-node-dataset": "error",
      "unicorn/error-message": "error",
      "unicorn/explicit-timer-delay": "error",
      "unicorn/no-accidental-bitwise-operator": "off",
      "unicorn/no-array-concat-in-loop": "error",
      "unicorn/no-array-fill-with-reference-type": "error",
      "unicorn/no-array-from-fill": "error",
      "unicorn/no-array-front-mutation": "off",
      "unicorn/no-array-method-this-argument": "error",
      "unicorn/no-array-sort-for-min-max": "error",
      "unicorn/no-array-splice": "error",
      "unicorn/no-asterisk-prefix-in-documentation-comments": "error",
      "unicorn/no-await-expression-member": "error",
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-blob-to-file": "error",
      "unicorn/no-boolean-sort-comparator": "error",
      "unicorn/no-break-in-nested-loop": "off",
      "unicorn/no-canvas-to-image": "error",
      "unicorn/no-chained-comparison": "error",
      "unicorn/no-collection-bracket-access": "error",
      "unicorn/no-computed-property-existence-check": "error",
      "unicorn/no-confusing-array-splice": "error",
      "unicorn/no-confusing-array-with": "error",
      "unicorn/no-constant-zero-expression": "error",
      "unicorn/no-declarations-before-early-exit": "error",
      "unicorn/no-double-comparison": "error",
      "unicorn/no-duplicate-if-branches": "error",
      "unicorn/no-duplicate-logical-operands": "error",
      "unicorn/no-duplicate-loops": "error",
      "unicorn/no-duplicate-set-values": "error",
      "unicorn/no-error-property-assignment": "error",
      "unicorn/no-for-each": "off",
      "unicorn/no-global-object-property-assignment": "error",
      "unicorn/no-immediate-mutation": "error",
      "unicorn/no-impossible-length-comparison": "error",
      "unicorn/no-incorrect-query-selector": "error",
      "unicorn/no-invalid-character-comparison": "error",
      "unicorn/no-invalid-fetch-options": "error",
      "unicorn/no-invalid-remove-event-listener": "error",
      "unicorn/no-invalid-well-known-symbol-methods": "error",
      "unicorn/no-late-current-target-access": "error",
      "unicorn/no-late-event-control": "error",
      "unicorn/no-loop-iterable-mutation": "error",
      "unicorn/no-magic-array-flat-depth": "error",
      "unicorn/no-mismatched-map-key": "error",
      "unicorn/no-misrefactored-assignment": "error",
      "unicorn/no-negated-array-predicate": "error",
      "unicorn/no-negation-in-equality-check": "error",
      "unicorn/no-nonstandard-builtin-properties": "off",
      "unicorn/no-object-methods-with-collections": "error",
      "unicorn/no-redundant-comparison": "error",
      "unicorn/no-return-array-push": "error",
      "unicorn/no-selector-as-dom-name": "error",
      "unicorn/no-single-promise-in-promise-methods": "error",
      "unicorn/no-subtraction-comparison": "error",
      "unicorn/no-thenable": "error",
      "unicorn/no-top-level-side-effects": "error",
      "unicorn/no-typeof-undefined": "off",
      "unicorn/no-uncalled-method": "error",
      "unicorn/no-unnecessary-array-flat-depth": "error",
      "unicorn/no-unnecessary-array-splice-count": "error",
      "unicorn/no-unnecessary-boolean-comparison": "error",
      "unicorn/no-unnecessary-global-this": "error",
      "unicorn/no-unnecessary-nested-ternary": "error",
      "unicorn/no-unnecessary-slice-end": "error",
      "unicorn/no-unnecessary-splice": "error",
      "unicorn/no-unreadable-for-of-expression": "error",
      "unicorn/no-unreadable-new-expression": "error",
      "unicorn/no-unreadable-object-destructuring": "error",
      "unicorn/no-unsafe-buffer-conversion": "error",
      "unicorn/no-unsafe-dom-html": "error",
      "unicorn/no-unsafe-property-key": "error",
      "unicorn/no-unsafe-string-replacement": "error",
      "unicorn/no-unused-array-method-return": "off",
      "unicorn/no-useless-boolean-cast": "error",
      "unicorn/no-useless-collection-argument": "error",
      "unicorn/no-useless-compound-assignment": "error",
      "unicorn/no-useless-concat": "error",
      "unicorn/no-useless-continue": "error",
      "unicorn/no-useless-delete-check": "error",
      "unicorn/no-useless-else": "off",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-iterator-to-array": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-logical-operand": "error",
      "unicorn/no-useless-override": "error",
      "unicorn/no-useless-promise-resolve-reject": "error",
      "unicorn/no-useless-recursion": "error",
      "unicorn/no-xor-as-exponentiation": "error",
      "unicorn/prefer-abort-signal-timeout": "error",
      "unicorn/prefer-add-event-listener-options": "error",
      "unicorn/prefer-aggregate-error": "error",
      "unicorn/prefer-array-from-async": "error",
      "unicorn/prefer-array-from-map": "error",
      "unicorn/prefer-array-iterable-methods": "error",
      "unicorn/prefer-array-last-methods": "error",
      "unicorn/prefer-array-slice": "error",
      "unicorn/prefer-at": "error",
      "unicorn/prefer-await": "off",
      "unicorn/prefer-bigint-literals": "error",
      "unicorn/prefer-boolean-return": "error",
      "unicorn/prefer-classlist-toggle": "error",
      "unicorn/prefer-continue": "off",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-direct-iteration": "error",
      "unicorn/prefer-dispose": "error",
      "unicorn/prefer-dom-node-append": "error",
      "unicorn/prefer-dom-node-html-methods": "error",
      "unicorn/prefer-dom-node-remove": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-dom-node-replace-children": "error",
      "unicorn/prefer-early-return": "off",
      "unicorn/prefer-error-is-error": "error",
      "unicorn/prefer-import-meta-properties": "error",
      "unicorn/prefer-iterable-in-constructor": "error",
      "unicorn/prefer-iterator-concat": "error",
      "unicorn/prefer-iterator-to-array": "error",
      "unicorn/prefer-iterator-to-array-at-end": "error",
      "unicorn/prefer-flat-math-min-max": "error",
      "unicorn/prefer-get-or-insert-computed": "error",
      "unicorn/prefer-global-this": "off",
      "unicorn/prefer-has-check": "error",
      "unicorn/prefer-hoisting-branch-code": "error",
      "unicorn/prefer-location-assign": "error",
      "unicorn/prefer-map-from-entries": "error",
      "unicorn/prefer-math-abs": "error",
      "unicorn/prefer-math-constants": "error",
      "unicorn/prefer-math-min-max": "error",
      "unicorn/prefer-modern-dom-apis": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-number-coercion": "off",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-object-define-properties": "error",
      "unicorn/prefer-object-destructuring-defaults": "error",
      "unicorn/prefer-object-from-entries": "error",
      "unicorn/prefer-object-iterable-methods": "error",
      "unicorn/prefer-observer-apis": "error",
      "unicorn/prefer-path2d": "error",
      "unicorn/prefer-promise-try": "error",
      "unicorn/prefer-promise-with-resolvers": "error",
      "unicorn/prefer-prototype-methods": "error",
      "unicorn/prefer-query-selector": "error",
      "unicorn/prefer-queue-microtask": "error",
      "unicorn/prefer-reflect-apply": "error",
      "unicorn/prefer-regexp-escape": "error",
      "unicorn/prefer-regexp-test": "error",
      "unicorn/prefer-response-static-json": "error",
      "unicorn/prefer-scoped-selector": "error",
      "unicorn/prefer-set-methods": "error",
      "unicorn/prefer-single-call": "error",
      "unicorn/prefer-single-replace": "error",
      "unicorn/prefer-split-limit": "off",
      "unicorn/prefer-string-pad-start-end": "error",
      "unicorn/prefer-string-raw": "error",
      "unicorn/prefer-string-repeat": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-structured-clone": "error",
      "unicorn/prefer-temporal": "off",
      "unicorn/prefer-toggle-attribute": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/prefer-uint8array-base64": "error",
      "unicorn/prefer-unary-minus": "error",
      "unicorn/prefer-unicode-code-point-escapes": "error",
      "unicorn/prefer-url-can-parse": "error",
      "unicorn/prefer-url-href": "error",
      "unicorn/prefer-while-loop-condition": "error",
      "unicorn/relative-url-style": ["error", "never"],
      "unicorn/require-array-sort-compare": "off",
      "unicorn/require-css-escape": "error",
      "unicorn/require-passive-events": "off",
      "unicorn/require-proxy-trap-boolean-return": "error",

      ...overrides,
    },
  };
}
