export enum Glob {
  All = '**/*.?([cm])[jt]s?(x)',
  Javascript = '**/*.?([cm])js?(x)',
  Svelte = '**/*.svelte',
  Typescript = '**/*.?([cm])ts?(x)',
  Vue = '**/*.vue',
}

export enum GlobIgnore {
  Autogenerated = '**/autogenerated',
  Cache = '**/cache',
  Dist = '**/dist',
  Log = '**/log?(s)',
  NodeModules = '**/node_modules',
  Out = '**/out',
  SvelteKit = '**/.svelte-kit',
  Target = '**/target',
  Temp = '**/?(.)temp',
}
